### ISSUE TITLE
"just unpack"-- how?

### ISSUE THREAD

**Issue by NQNStudios** [Simn/mingw64-mbedtls#1]
(My use-case is, I'm trying to build Haxe from source on Windows 10. I haven't used Cygwin very much so I'm figuring things out as I go whenever I get a bug the docs don't mention. I got [this bug](https://github.com/HaxeFoundation/haxe/issues/9251) and followed the link to this repo.)

I'm new to Cygwin and it's not clear to me how to unpack this in my cygwin root.

More specifically:

- Does cygwin root refer to C:/cygwin64 where I chose the default root install directory, or C:/cygwin where I chose the local package directory? Writing this out now, it seems obvious, but in the moment trying to figure things out as a newb, it wasn't.
- I assumed to unpack the version corresponding to my 64-bit architecture, all I had to do was download the raw file `mingw64-x86_64.cygport`.
- Not knowing how to "unpack" a .cygport file, I googled cygport and figured I must need to run the Cygwin installer again to install the `cygport` program.
- the `cygport` CLI help text doesn't have anything called "unpack" so I started by trying `cygport mingw64-x86_64.cygport install` and I get the unhelpful message `*** ERROR: mingw64-x86_64.cygport not found.` This is with my working directory at root, and the file present. Why wouldn't the file be found?
- I opened the `.cygport` file and noticed it referenced another file from the repo which I didn't download. So I go back and download that, thinking maybe the error message is *really* because of this other file. But I tried again and it isn't.

That's as far as I've gotten. If I figure it out on my own, I'd be happy to send a PR with better instructions in README.md.

**Comment by Simn** [comment]
You really just have to unpack https://github.com/Simn/mingw64-mbedtls/releases into `c:\cygwin64`.

**Comment by NQNStudios** [comment]
Thanks for your help!
